### PR TITLE
Deduplicate the base pages

### PR DESCRIPTION
**Pull request by akkuldn**
In this PR i have deduplicated the Base Page and Mobile Base Pages by sorting out the common functionalities in to separate helper classes. 
- There are four helper classes` logging_objects`, `remote_objects`, `selenium_objects`, `screenshot_objects`
- The new helper classes resides under `page_objects/core_helpers`
- Have also modified overwrite flag as a configurable entity

### CODE REVIEW

**Comment by indiranell** [comment]
@akkuldn  Here are my Observations

1. In the method `screenshot_directory` , please include a docstring to explain its functionality, 
2. In the method `get_test_name`, please add a docstring detailing what this method does
3. The overwrite_flag logic in this method seems to be incorrect. When overwrite_flag is true, instead of deleting the existing screenshot directory, the code renames the existing directory by appending an integer  When overwrite_flag is false, the code deletes the existing directory. How did you test this?
4. import conf.screenshot_conf can be removed in base_page.py
5. One suggestion is to rename selenium_objects.py to selenium_action_objects. py  reflecting that the file contains action methods.
6. I think you can move these methods also into selenium_objects.py  (or the newly named selenium_action_objects.py) because these are also action methods
    hit_enter
    scroll_down
    hover 
7.  The log messages summary must show the method name from which it is generated in the log message like this. 
```
2024-03-19 12:26:12.962 | INFO     | utils.Base_Logging:write:98 - set_name | Set the name to: knight
2024-03-19 12:26:13.338 | INFO     | utils.Base_Logging:write:98 - test_example_form | PASS: Name was successfully 
set to: knight

But It is showing `write` and `success`. 
```
2024-03-20 14:02:15.875 | INFO     | utils.Base_Logging:write:98 - write | Set the name to: knight
2024-03-20 14:02:16.743 | INFO     | utils.Base_Logging:write:98 - success | PASS: Name was successfully set to: knight

2024-03-20 14:02:16.790 | INFO     | utils.Base_Logging:write:98 - write | Script duration: 4 seconds
```
8. Any specific reasons for not moving set_screenshot_dir and get_screenshot_dir into screenshot_objects.py?

**Comment by akkuldn** [comment]
> @akkuldn Here are my Observations
> 
> 1. In the method `screenshot_directory` , please include a docstring to explain its functionality,
> 2. In the method `get_test_name`, please add a docstring detailing what this method does
> 3. The overwrite_flag logic in this method seems to be incorrect. When overwrite_flag is true, instead of deleting the existing screenshot directory, the code renames the existing directory by appending an integer  When overwrite_flag is false, the code deletes the existing directory. How did you test this?
> 4. import conf.screenshot_conf can be removed in base_page.py
> 5. One suggestion is to rename selenium_objects.py to selenium_action_objects. py  reflecting that the file contains action methods.
> 6. I think you can move these methods also into selenium_objects.py  (or the newly named selenium_action_objects.py) because these are also action methods
>    hit_enter
>    scroll_down
>    hover
> 7. The log messages summary must show the method name from which it is generated in the log message like this.
> 
> ```
> 2024-03-19 12:26:12.962 | INFO     | utils.Base_Logging:write:98 - set_name | Set the name to: knight
> 2024-03-19 12:26:13.338 | INFO     | utils.Base_Logging:write:98 - test_example_form | PASS: Name was successfully 
> set to: knight
> ```
> 
> But It is showing `write` and `success`.
> 
> ```
> 2024-03-20 14:02:15.875 | INFO     | utils.Base_Logging:write:98 - write | Set the name to: knight
> 2024-03-20 14:02:16.743 | INFO     | utils.Base_Logging:write:98 - success | PASS: Name was successfully set to: knight
> 
> 2024-03-20 14:02:16.790 | INFO     | utils.Base_Logging:write:98 - write | Script duration: 4 seconds
> ```
> 
> 8. Any specific reasons for not moving set_screenshot_dir and get_screenshot_dir into screenshot_objects.py?

@indiranell 
1. Added docstring to `screenshot_directory` 
2. Added docstring to `get_test_name`
3. Modified the logic of  `overwrite_flag` 
4. Removed import of `conf.screenshot_conf`  in base_page.py
5. Renamed selenium_objects.py to selenium_action_objects. py 
6. Moved the methods `hit_enter`, `scroll_down`, `hover` to selenium_action_objects. py 
7. Fixed the log messages, it now shows the method names
8. `set_screenshot_dir` and `get_screenshot_dir` methods are different for base_page and mobile_base_page, so we cannot have it as a common method in screenshot_objects.py

**Comment by indiranell** [comment]
@akkuldn : The changes look good. I have also executed below tests and here are my observations.

1. Tested for selenium tests(Local) : Passed
2. Tested for selenium tests(Remote): Passed
3. Tested for Mobile tests(Remote) : Passed
4. Tested for API tests :  There is a difference in the method names display in the log messages. Please check

```
the log output from your branch:
2024-04-05 11:28:03.118 | INFO     | utils.Base_Logging:write:103 - log_result | PASS: Successfully added new car with 
details {'name': 'figo', 'brand': 'ford', 'price_range': '5-8 lacs', 'car_type': 'hatchback'}
2024-04-05 11:28:03.129 | INFO     | utils.Base_Logging:write:103 - log_result | ~~~~~~~~

log output from master:
2024-04-05 11:30:08.559 | INFO     | utils.Base_Logging:write:101 - success | PASS: Successfully added new car with details {'name': 'figo', 'brand': 'ford', 'price_range': '5-8 lacs', 'car_type': 'hatchback'}
2024-04-05 11:30:08.570 | INFO     | utils.Base_Logging:write:101 - write | ~~~~~~~~
```

**Comment by akkuldn** [comment]
> @akkuldn : The changes look good. I have also executed below tests and here are my observations.
> 
> 1. Tested for selenium tests(Local) : Passed
> 2. Tested for selenium tests(Remote): Passed
> 3. Tested for Mobile tests(Remote) : Passed
> 4. Tested for API tests :  There is a difference in the method names display in the log messages. Please check
> 
> ```
> the log output from your branch:
> 2024-04-05 11:28:03.118 | INFO     | utils.Base_Logging:write:103 - log_result | PASS: Successfully added new car with 
> details {'name': 'figo', 'brand': 'ford', 'price_range': '5-8 lacs', 'car_type': 'hatchback'}
> 2024-04-05 11:28:03.129 | INFO     | utils.Base_Logging:write:103 - log_result | ~~~~~~~~
> 
> log output from master:
> 2024-04-05 11:30:08.559 | INFO     | utils.Base_Logging:write:101 - success | PASS: Successfully added new car with details {'name': 'figo', 'brand': 'ford', 'price_range': '5-8 lacs', 'car_type': 'hatchback'}
> 2024-04-05 11:30:08.570 | INFO     | utils.Base_Logging:write:101 - write | ~~~~~~~~
> ```

Hi @indiranell ,  Sorry for the delayed response.  I discussed this API log display issue in the Standup session. Arun and Rohan seem to like the new method names displayed than the previous one and suggested to keep it that way. I felt the same, What do you think is better, the previous names or the method names displayed in this PR?

**Review by indiranell — APPROVED** [review]

**Pull request merged**
