### PR TITLE
changed if elif pattern in pytest report summary

### PR DESCRIPTION
**Pull request by rahul-qxf2**
In this pull request, I have changed if loop to else, in the pytest_terminal_summary() method in the `conftest.py` file.

### CODE REVIEW

**Comment by qxf2** [comment]
This does not seem to be the right change. What happens if someone wants to report to tesults and Slack? I think 3 ifs might be a better choice.

Also @rohanj-qxf2 - why is Codacity check not triggering for Rahul? Do I (or Rahul) need to be enabling something for his account?

**Comment by rohanj-qxf2** [comment]
@qxf2 Did you change any settings on codacy recently if not can you check codacy has access to publish results back to github ,this commit is a up to the standards - https://app.codacy.com/manual/qxf2/qxf2-page-object-model/commit?bid=16560353&cid=465899486

**Comment by rahul-qxf2** [comment]
> This does not seem to be the right change. What happens if someone wants to report to tesults and Slack? I think 3 ifs might be a better choice.
>  I have changed this to elif now. Hope this should be fine codecy checks are passing as well now.
https://app.codacy.com/manual/qxf2/qxf2-page-object-model/pullRequest?prid=5447840
> Also @rohanj-qxf2 - why is Codacity check not triggering for Rahul? Do I (or Rahul) need to be enabling something for his account? Asking because Rahul's commit has trailing whitespaces.

**Comment by rahul-qxf2** [comment]
> > This does not seem to be the right change. What happens if someone wants to report to tesults and Slack? I think 3 ifs might be a better choice.
> > I have changed this to elif now. Hope this should be fine codecy checks are passing as well now.
> > https://app.codacy.com/manual/qxf2/qxf2-page-object-model/pullRequest?prid=5447840
> > Also @rohanj-qxf2 - why is Codacity check not triggering for Rahul? Do I (or Rahul) need to be enabling something for his account? Asking because Rahul's commit has trailing whitespaces.

**Comment by qxf2** [comment]
Rahul can this made 3 separate ifs (not 1 if and 2 elif). My reasoning is that 3 separate if statements will let you report results to more than 1 endpoint. Right now, if a user chooses to get results emailed, the they can't use tesults or slack.

**Comment by qxf2** [comment]
@rohanj-qxf2 I have not made changes to codacy.

**Comment by rahul-qxf2** [comment]
> Rahul can this made 3 separate ifs (not 1 if and 2 elif). My reasoning is that 3 separate if statements will let you report results to more than 1 endpoint. Right now, if a user chooses to get results emailed, the they can't use tesults or slack.

I have done the changes CI & Codecy checks are passed now as well.
https://app.codacy.com/manual/qxf2/qxf2-page-object-model/pullRequest?prid=5447840

Let me know in case you have any further comments.

**Pull request merged**
