### PR TITLE
Modified the Endpoint objects to inherit from BaseAPI object

### PR DESCRIPTION
**Pull request by shivahari**
PR to fix [issue #454](https://github.com/qxf2/qxf2-page-object-model/issues/454)

Changes tracked in the PR:
1.  The `Endpoint` objects are modified to inherit from `BaseAPI` object.
2. The `Endpoint` objects are renamed based on on `pep8` recommendations.
3. The `BaseAPI` class initializes `requests` module used to implement the API Automation framework.
4.  The changes for [issue #452](https://github.com/qxf2/qxf2-page-object-model/issues/452) from [fix_api_logging](https://github.com/qxf2/qxf2-page-object-model/tree/fix_api_logging) branch.

### CODE REVIEW

**Review by avinash010 — COMMENTED** [review]
@shivahari 
* In few places in api_player.py files we missed adding 2 lines after each functions
* When running async test i don see the complete test logs. I see an exception. I am using Python 3.12.3

```tests/test_api_async_example.py::test_api_async_example 2024-10-15 12:51:04.385 | INFO     | /tests/test_api_async_example.py::test_api_async_example | Exception when trying to run test: /home/avinash/qxf2/qxf2_pom/qxf2-page-object-model/tests/test_api_async_example.py
2024-10-15 12:51:04.388 | INFO     | /tests/test_api_async_example.py::test_api_async_example | Python says: unhandled errors in a TaskGroup (1 sub-exception)
PASSED```

**Comment by shivahari** [comment]
> @shivahari
> 
> * In few places in api_player.py files we missed adding 2 lines after each functions
> * When running async test i don see the complete test logs. I see an exception. I am using Python 3.12.3
> 
> ```
> 2024-10-15 12:51:04.388 | INFO     | /tests/test_api_async_example.py::test_api_async_example | Python says: unhandled errors in a TaskGroup (1 sub-exception)
> PASSED```
> ```

This issue is because of changes that need to be made to accommodate fixes from [fix-api-logging](https://github.com/qxf2/qxf2-page-object-model/tree/fix_api_logging).

I have now modified:
1. `API_Player` module to use the right object types after fixes from `fix-api-logging` branch.
2. The `Async` test to raise the exception rather than printing it. This will prevent the test from being wrongly markes `Passed` when there is a failure

**Comment by shivahari** [comment]
Improved formatting in `API_Player` module - Added `2` lines after each methods

**Review by avinash010 — APPROVED** [review]

**Review by rohandudam — APPROVED** [review]
Noticed log levels for all logs are set to Info But this will auto fixed once we start using logging_objects module instead of utils/results module.

**Pull request merged**
