### PR TITLE
updating chrome browser version

### PR DESCRIPTION
**Pull request by Archana-GS**
- Updating the browsers and drivers to latest version
- Updating the python3-pip from `22.0.2+dfsg-1ubuntu0.2` to `22.0.2+dfsg-1ubuntu0.3`

### CODE REVIEW

**Comment by avinash010** [comment]
@Archana-GS Why did you open this PR? I dont think the browser will get outdated so fast. The browser will release new version every few days. Doesn't mean that we need to keep on updating it

**Comment by Archana-GS** [comment]
> @Archana-GS Why did you open this PR? I dont think the browser will get outdated so fast. The browser will release new version every few days. Doesn't mean that we need to keep on updating it

@avinash010 I tried to build an image by using the previous version of chrome browser that didn't work so updated with latest version , its working fine now

**Comment by avinash010** [comment]
@Archana-GS Can you look for an alternate. We cant always download latest version
https://www.browserstack.com/guide/downgrade-to-older-versions-of-chrome

**Review by avinash010 — COMMENTED** [review]
@Archana-GS I see a codacy issue for this change. Can we resolve this https://app.codacy.com/gh/qxf2/qxf2-page-object-model/pullRequest?prid=12101467

**Pull request merged**
