### PR TITLE
Made reporting tools architectural changes

### PR DESCRIPTION
**Pull request by rohandudam**
Created new directory "reporting_tools under integrations and moved TestRail and Tesults integration files. Made appropriate changes so integration can not break.

### CODE REVIEW

**Review by indiranell — COMMENTED** [review]
@rohandudam  Here are few Observations from Sravanti and me:
1.  In file `conftest.py`, the line 34 which print out the Exception messages looks outdated. The command `pytest -X Y -R 100` doesn't work. Get `pytest: error: unrecognized arguments: -X -R 100` error. May be it will not be relevant once we remove setup_testrail.py. Please confirm
2. Please remove `self.testrail_flag = False` from Base_Page.py and Mobile_Base_Page.py
3. Observed that `add_tesults_case` is still in Base_Page.py file. Any specific reason?

Test Run - Tesults
image

**Comment by rohandudam** [comment]
@indiranell @sravantit25 Thanks for your review and suggestions.
I made changes as per your suggestion and moved add_tesults_case method under remote_object.py file. We need to keep it as part of base_page as we are calling this method from test.

Look at below screenshots related to changes:
TestRail Exception message update:
Screenshot from 2024-07-12 12-46-43

Tesult Test Run:
tesult_run

**Review by indiranell — APPROVED** [review]
Looks good to me

**Review by sravantit25 — APPROVED** [review]
Thanks for making the changes, Rohan. Looks good.

**Pull request merged**
